### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by TofuGG** [ClementDreptin/OpenNeighborhood-old#6]
>>git clone --recursive git@github.com:ClementDreptin/OpenNeighborhood.git
Cloning into 'OpenNeighborhood'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ClementDreptin** [comment]
It looks like you don't have your SSH public key registered in your GitHub account. There are 2 solutions to your problem:

- Adding your SSH public key to your GitHub account. Check the [docs](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) if you don't know how to do it.
- Cloning the repository using HTTPS with the command `git clone --recursive https://github.com/ClementDreptin/OpenNeighborhood.git`.

GitHub recommends cloning repositories using SSH and is being more and more restrictive on operations over HTTPS, so I recommend adding your SSH public key to your GitHub account.

Hope it helps.

**Comment by TofuGG** [comment]
Thanks!
the second one worked!!
