### ISSUE TITLE
zsh: parse error near `\n'

### ISSUE THREAD

**Issue by TofuGG** [ClementDreptin/OpenNeighborhood-old#7]
>>cd build && make config=<debug|release> 
zsh: parse error near `\n'
>>

**Comment by ClementDreptin** [comment]
`config=<debug|release>` means you're supposed to choose either `debug` or `release`, depending on the configuration you're looking for. So `cd build && make config=debug` for `debug` or `cd build && make config=release` for `release`. I thought this was pretty obvious...

Note: if you don't specify a config, `make` will automatically build the `debug` config.

**Comment by TofuGG** [comment]
I'm sorry I'm just new to this

**Comment by ClementDreptin** [comment]
It's ok, we all started somewhere 😉.

Little piece of advice for the future: when submitting an issue, try to bring a bit of context on what you did to get the error, what the error was, and what you tried to fix it. Here it just seemed like you copy-pasted the command, got an error and didn't try to do anything before posting the issue.
