### ISSUE TITLE
No files showing on Retail HDD on Linux Mint

### ISSUE THREAD

**Issue by shantz1403** [ClementDreptin/OpenNeighborhood-old#9]
Hi thanks for creating OpenNeighborhood for Linux. I am having some issues with launching my games from the program, like when I  am browsing on the Retail HDD and try to open any game folder no files are shown on Linux Mint.

![Screenshot from 2024-01-21 00-08-02](https://github.com/ClementDreptin/OpenNeighborhood/assets/157229749/d239214e-9755-4dc8-bc65-453315c971e0)

**Comment by ClementDreptin** [comment]
Hi, do you have a Windows machine with the official Xbox 360 Neighborhood installed to see if you also have the problem?

**Comment by shantz1403** [comment]
Yes I have 360 Neighborhood on Windows 7 machine and it works fine.

**Comment by ClementDreptin** [comment]
It's hard to tell where the problem could come from then. Maybe try to run OpenNeighborhood in a debugger to see if [XBDM](https://github.com/ClementDreptin/XBDM) is even finding your files. You can set a breakpoint in [`deps/XBDM/src/Console.cpp` at line 211](https://github.com/ClementDreptin/XBDM/blob/master/src/Console.cpp#L211) to see what the response looks like.

**Comment by shantz1403** [comment]
Hey thanks for the advise, I followed your steps and wow in debug mode i can see the files, so not sure whats happening while opening it normally?!
![working](https://github.com/ClementDreptin/OpenNeighborhood/assets/157229749/3416e0a8-8329-4b78-833f-bc5a0ad5dedc)

**Comment by ClementDreptin** [comment]
Sorry for not getting back to you earlier. I just made sure it worked on my Ubuntu 20.04 machine and it does, in both debug and release configurations. I'm afraid I might not be able to do much if I can't reproduce the bug. I know it's not a satisfying answer but if you absolutely need to browse your Xbox 360 on Linux, you can still do it in debug mode.

**Comment by shantz1403** [comment]
Hey its all good, going back to the program I found out that it works just have to bypass the error which gives could not find directory by going back 2 to 3 times and then opening the folder the files show on the release build. Once again thanks for all the help.
